services:
  postgres:
    image: postgres:15
    restart: always
    env_file:
      - .env
    ports:
      - '5432:5432'
    volumes:
      - postgres-data:/var/lib/postgresql/data
    networks:
      - chyra_network
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -d chyra_db -U user']
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:alpine
    restart: always
    ports:
      - '6379:6379'
    volumes:
      - redis-data:/data
    networks:
      - chyra_network
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 10s
      timeout: 3s
      retries: 3

  meilisearch:
    image: getmeili/meilisearch:v1.12.1
    env_file:
      - .env
    container_name: meilisearch
    restart: always
    ports:
      - '7700:7700'
    volumes:
      - meilisearch_data:/meili_data
    networks:
      - chyra_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:7700/health']
      interval: 10s
      timeout: 3s
      retries: 3

  api:
    image: retier/chyra-api:latest
    restart: always
    env_file:
      - .env
    depends_on:
      redis:
        condition: service_healthy # Wait for healthcheck
      meilisearch:
        condition: service_healthy # Wait for healthcheck
      postgres:
        condition: service_healthy # Wait for healthcheck
    networks:
      - chyra_network
    ports:
      - '8080:8080'
    command: >
      sh -c "
        pnpm dlx prisma migrate deploy &&
        pnpm start
      "
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:8080/health']
      interval: 10s
      timeout: 3s
      retries: 3

  client:
    image: retier/chyra-client:latest
    restart: always
    ports:
      - '4173:4173'
    depends_on:
      - api
    networks:
      - chyra_network
    healthcheck:
      test: ['CMD', 'curl', '-f', 'http://localhost:4173']
      interval: 10s
      timeout: 3s
      retries: 3

  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: always
    depends_on:
      - api
      - client
    ports:
      - '80:80'
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - chyra_network
networks:
  chyra_network:
    driver: bridge

volumes:
  postgres-data:
  redis-data:
  meilisearch_data:
