export const DI_TYPES = {
  PrismaClient: Symbol.for('PrismaClient'),
  CacheService: Symbol.for('CacheService'),

  SearchService: Symbol.for('SearchService'),
  Logger: Symbol.for('Logger'),
  Mailer: Symbol.for('Mailer'),
  MessageBroker: Symbol.for('MessageBroker'),

  UserRepository: Symbol.for('UserRepository'),
  AuthRepository: Symbol.for('AuthRepository'),
  AuthorRepository: Symbol.for('AuthorRepository'),
  CategoryRepository: Symbol.for('CategoryRepository'),
  PublisherRepository: Symbol.for('PublisherRepository'),
  GenreRepository: Symbol.for('GenreRepository'),
  SerieRepository: Symbol.for('SerieRepository'),
  BookRepository: Symbol.for('BookRepository'),

  UserService: Symbol.for('UserService'),
  AuthorService: Symbol.for('AuthorService'),
  AuthService: Symbol.for('AuthService'),
  CategoryService: Symbol.for('CategoryService'),
  PublisherService: Symbol.for('PublisherService'),
  GenreService: Symbol.for('GenreService'),
  SerieService: Symbol.for('SerieService'),
  BookService: Symbol.for('BookService'),

  UserController: Symbol.for('UserController'),
  AuthController: Symbol.for('AuthController'),
  AuthorController: Symbol.for('AuthorController'),
  CategoryController: Symbol.for('CategoryController'),
  PublisherController: Symbol.for('PublisherController'),
  GenreController: Symbol.for('GenreController'),
  SerieController: Symbol.for('SerieController'),
  BookController: Symbol.for('BookController'),

  UserRouter: Symbol.for('UserRouter'),
  AuthRouter: Symbol.for('AuthRouter'),
  AuthorRouter: Symbol.for('AuthorRouter'),
  CategoryRouter: Symbol.for('CategoryRouter'),
  PublisherRouter: Symbol.for('PublisherRouter'),
  GenreRouter: Symbol.for('GenreRouter'),
  SerieRouter: Symbol.for('SerieRouter'),
  BookRouter: Symbol.for('BookRouter'),
};
